### ISSUE TITLE
tck files in the connectome2tck folder don't open

### ISSUE THREAD

**Issue by mayayab** [PennLINC/qsirecon#117]
## Summary
The tck files in the **connectome2tck** folders don't load in typical viewers (MI-Brain crashes, mrview gives a "bad file format" error: "mrview: [ERROR] unknown format for image "<MYPATH>/qsirecon-MRtrix3_act-None/sub-xx/ses-2/dwi/connectome2tck/sub-xx_ses-2_space-T1w_desc-preproc_schaefer400_radius2_meanlength_c2t_exemplars.tck"
This is the case for all the .tck files extracted from the zipped folder **sub-xxx_ses-2_space-T1w_desc-preproc_exemplarbundles.zip**
(but the main xxx_streamlines.tck file is correct and opens as expected) 

## Additional details

- QSIRecon version: qsiprep version 22.1, using the mrTrix_act_None reconstruction json file.

**Comment by araikes** [comment]
@mayayab,

Using the `mrtrix_multishell_msmt_ACT-hsvs` recon spec, I cannot replicate this. Mine load just fine in mrview. Can you clarify that you're loading an image first in mrview (like the white matter FOD `mif.gz` file) and then loading the `tck` file using the tractography tab?

![image](https://github.com/user-attachments/assets/fc3c620c-e72b-44e1-b003-2b65d775c824)

**Comment by mattcieslak** [comment]
@mayayab The issue is that you're trying to open the tck file with mrview instead of opening a mif file and loading the tck file with the streamlines tool. Please reopen the issue if that's still giving you trouble
