### ISSUE TITLE
Datasinks don't work for all of the expected files 

### ISSUE THREAD

**Issue by araikes** [PennLINC/qsirecon#122]
## Summary

In the current version of `qsirecon`, outputs aren't written for `reorient_fslstd`. All of the output entities fail on `DerivativeSink` for essentially the same reason and appears to be the same issue as in #112:

```
Node: qsirecon_0_23_wf.sub-001_reorient2fslstd.sub_001_ses_01_dir_AP_run_001_space_T1w_desc_preproc_recon_wf.to_fslstd.ds_dwi_to_fslstd
Working directory: /tmp/qsirecon_0_23_wf/sub-001_reorient2fslstd/sub_001_ses_01_dir_AP_run_001_space_T1w_desc_preproc_recon_wf/to_fslstd/ds_dwi_to_fslstd

Node inputs:

acquisition = <undefined>
atlas = <undefined>
base_directory = /output/derivatives/qsirecon-FSL
bundle = <undefined>
bundles = <undefined>
ceagent = <undefined>
check_hdr = True
chunk = <undefined>
cohort = <undefined>
compress = <undefined>
data_dtype = <undefined>
datatype = <undefined>
den = <undefined>
desc = <undefined>
direction = <undefined>
dismiss_entities = ['desc']
echo = <undefined>
extension = bvec
flip = <undefined>
fmap = <undefined>
from = <undefined>
hemi = <undefined>
in_file = ['/tmp/qsirecon_0_23_wf/sub-001_reorient2fslstd/sub_001_ses_01_dir_AP_run_001_space_T1w_desc_preproc_recon_wf/to_fslstd/convert_to_fsl/sub-001_ses-01_dir-AP_run-001_space-T1w_desc-preproc_dwi_LAS.nii.gz']
inv = <undefined>
label = <undefined>
meta_dict = <undefined>
modality = <undefined>
mode = <undefined>
model = <undefined>
mt = <undefined>
nucleus = <undefined>
param = <undefined>
part = <undefined>
proc = <undefined>
reconstruction = <undefined>
recording = <undefined>
res = <undefined>
roi = <undefined>
run = <undefined>
sample = <undefined>
scans = <undefined>
session = <undefined>
source_file = ['/input/sub-001/ses-01/dwi/sub-001_ses-01_dir-AP_run-001_space-T1w_desc-preproc_dwi.nii.gz']
space = <undefined>
staining = <undefined>
subject = <undefined>
subset = <undefined>
suffix = dwi
task = <undefined>
to = <undefined>
tracer = <undefined>
tracksys = <undefined>
volume = <undefined>

Traceback (most recent call last):
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node ds_dwi_to_fslstd.

Traceback:
	Traceback (most recent call last):
	  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 397, in run
	    runtime = self._run_interface(runtime)
	  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/niworkflows/interfaces/bids.py", line 632, in _run_interface
	    raise ValueError(f"Could not build path with entities {out_entities}.")
	ValueError: Could not build path with entities {'subject': '001', 'session': '01', 'direction': 'AP', 'run': '001', 'space': 'T1w', 'suffix': 'dwi', 'datatype': 'dwi', 'extension': 'bvec'}.
```

## Additional details

- QSIRecon version: 0.23.1
- Singularity version: 1.3.2-1.el7

## Reproducing the bug

```
apptainer run -\
-containall --writable-tmpfs \
-B $PWD/derivatives/qsiprep_0.22.1/qsiprep:/input \
-B $PWD/derivatives/qsirecon:/output \
-B /tmp:/tmp \
-B /groups/adamraikes/license.txt:/license.txt \
$RECON /input /output participant \
--participant_label 001 \
-w /tmp  \
--nthreads 8 --omp-nthreads 8 --fs-license-file /license.txt --recon-spec reorient_fslstd --input-type qsiprep 
```

**Comment by araikes** [comment]
Update: I ran (almost) all of the pipelines, just to look for failures like this, on the same individual. Here's the results:

The specific error takes the following form with the variance in the final `ValueError`:
```
Traceback (most recent call last):
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node ds_dwi_to_fslstd.

Traceback:
	Traceback (most recent call last):
	  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 397, in run
	    runtime = self._run_interface(runtime)
	  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/niworkflows/interfaces/bids.py", line 632, in _run_interface
	    raise ValueError(f"Could not build path with entities {out_entities}.")
	ValueError: Could not build path with entities {'subject': '001', 'session': '01', 'direction': 'AP', 'run': '001', 'space': 'T1w', 'suffix': 'dwi', 'datatype': 'dwi', 'extension': 'bvec'}.
```

Organizing this by pipeline and only tagging in the `Node` and final `ValueError` **(Please note that the this is a multisession subject and all errors occur for both sessions and I'm only reporting it for one of them)** 

### MRtrix ACT HSVS
`Node: qsirecon_0_23_wf.sub-001_mrtrix_multishell_msmt_hsvs.recon_anatomical_wf.ds_fs_5tt_hsvs`
`ValueError: Could not build path with entities {'subject': '001', 'suffix': 'dseg', 'datatype': 'anat', 'extension': 'mif.gz', 'space': 'fsnative', 'desc': 'hsvs'}.`

`Node: qsirecon_0_23_wf.sub-001_mrtrix_multishell_msmt_hsvs.recon_anatomical_wf.ds_qsiprep_5tt_hsvs`
`ValueError: Could not build path with entities {'subject': '001', 'suffix': 'dseg', 'datatype': 'anat', 'extension': 'nii', 'space': 'T1w', 'atlas': 'hsvs'}.`

### Multishell Scalarfest
`Node: qsirecon_0_23_wf.sub-001_multishell_scalarfest.sub_001_ses_01_dir_AP_run_001_space_T1w_desc_preproc_recon_wf.csdsi_3dshore.ds_extrap_bval`
`ValueError: Could not build path with entities {'subject': '001', 'session': '01', 'direction': 'AP', 'run': '001', 'space': 'T1w', 'suffix': 'dwi', 'datatype': 'dwi', 'extension': '.bval', 'desc': 'extrapolated'}.`

`Node: qsirecon_0_23_wf.sub-001_multishell_scalarfest.sub_001_ses_01_dir_AP_run_001_space_T1w_desc_preproc_recon_wf.csdsi_3dshore.ds_extrap_b`
`ValueError: Could not build path with entities {'subject': '001', 'session': '01', 'direction': 'AP', 'run': '001', 'space': 'T1w', 'suffix': 'dwi', 'datatype': 'dwi', 'extension': '.b', 'desc': 'extrapolated'}.`

`Node: qsirecon_0_23_wf.sub-001_multishell_scalarfest.sub_001_ses_01_dir_AP_run_001_space_T1w_desc_preproc_recon_wf.csdsi_3dshore.ds_extrap_bvec`
`ValueError: Could not build path with entities {'subject': '001', 'session': '01', 'direction': 'AP', 'run': '001', 'space': 'T1w', 'suffix': 'dwi', 'datatype': 'dwi', 'extension': '.bvec', 'desc': 'extrapolated'}.`

### Reorient to FSL 
`Node: qsirecon_0_23_wf.sub-001_reorient2fslstd.sub_001_ses_02_dir_AP_run_001_space_T1w_desc_preproc_recon_wf.to_fslstd.ds_mask_to_fslstd`
`ValueError: Could not build path with entities {'subject': '001', 'session': '01', 'direction': 'AP', 'run': '001', 'space': 'T1w', 'suffix': 'mask', 'datatype': 'dwi', 'extension': 'nii'}.`

`Node: qsirecon_0_23_wf.sub-001_reorient2fslstd.sub_001_ses_02_dir_AP_run_001_space_T1w_desc_preproc_recon_wf.to_fslstd.ds_bval_to_fslstd`
`ValueError: Could not build path with entities {'subject': '001', 'session': '02', 'direction': 'AP', 'run': '001', 'space': 'T1w', 'suffix': 'dwi', 'datatype': 'dwi', 'extension': 'bval'}.`

`Node: qsirecon_0_23_wf.sub-001_reorient2fslstd.sub_001_ses_02_dir_AP_run_001_space_T1w_desc_preproc_recon_wf.to_fslstd.ds_bvec_to_fslstd`
`ValueError: Could not build path with entities {'subject': '001', 'session': '02', 'direction': 'AP', 'run': '001', 'space': 'T1w', 'suffix': 'dwi', 'datatype': 'dwi', 'extension': 'bvec'}.`

`Node: qsirecon_0_23_wf.sub-001_reorient2fslstd.sub_001_ses_02_dir_AP_run_001_space_T1w_desc_preproc_recon_wf.to_fslstd.ds_dwi_to_fslstd`
`ValueError: Could not build path with entities {'subject': '001', 'session': '02', 'direction': 'AP', 'run': '001', 'space': 'T1w', 'suffix': 'dwi', 'datatype': 'dwi', 'extension': 'bvec'}.` **<- this one seems especially problematic since it appears to be trying to write the bvec file when you'd expect it to write the NIFTI**

### TORTOISE 
No errors

### DSI Studio autotrack
No errors

### DSI Studio GQI
No errors

### PyAFQ 
Other errors not related to this

**Comment by mattcieslak** [comment]
@araikes THANK YOU for testing these all out and putting the results in one place! Sure enough, the workflows that we don't have CI tests for all have problems.

**Comment by araikes** [comment]
No problem. Happy to help.
