### ISSUE TITLE
Connectivity matrix plots in reports are broken

### ISSUE THREAD

**Issue by araikes** [PennLINC/qsirecon#128]
## Summary

Reports are rendering (when using `--writable-tmpfs`) which is great. However, the connectivity matrix plots for DSI Studio GQI and MRtrix recon specs are not rendered in.

## Additional details

- QSIRecon version: 0.23.1
- Singularity version: 1.3.2-1.el7

### What were you trying to do?
Test out pipelines and look for failure points.

### What did you expect to happen?
Unanticipated failures

### What actually happened?
Unanticipated failures. The pngs don't appear to be pngs specifically for the connectivity matrices.

## Reproducing the bug

```
apptainer run -\
-containall --writable-tmpfs \
-B $PWD/derivatives/qsiprep_0.22.1/qsiprep:/input \
-B $PWD/derivatives/qsirecon:/output \
-B /tmp:/tmp \
-B /groups/adamraikes/license.txt:/license.txt \
$RECON /input /output participant \
--participant_label 001 \
-w /tmp  \
--nthreads 8 --omp-nthreads 8 --fs-license-file /license.txt --recon-spec dsi_studio_gqi --input-type qsiprep
``` 

### Report
![image](https://github.com/user-attachments/assets/06be555a-b0d0-4290-8fed-7755e68beeb4)

### Opening the PNG by itself
![image](https://github.com/user-attachments/assets/a8e6962b-c078-45bc-b7ef-062d66ef68b6)

**Comment by mattcieslak** [comment]
@tsalo has a fix for this in #131/#136
