### ISSUE TITLE
Document versioning scheme and QSIPrep compatibility

### ISSUE THREAD

**Issue by tsalo** [PennLINC/qsirecon#153]
I don't know if we've fleshed out the QSIPrep-QSIRecon versioning scheme yet, but this came up in a conversion with @cookpa.

Here's what I propose:

1. Commit to using the same versioning system for both QSIPrep and QSIRecon.
    - I don't have a strong opinion about what that versioning scheme should be. I just think it needs to be consistent.
2. Any changes that break backwards compatibility either internally _or_ between the two workflows should result in a new major release.
3. Following from (2), within a major release series, we expect compatibility across workflows.

Anything else?

**Comment by tsalo** [comment]
@mattcieslak WDYT of this proposal?

**Comment by mattcieslak** [comment]
The upcoming release will be the first major change (ever) in how the outputs are named. I'm good with either versioning system. Switching to the nipreps style would make it clear that there is a big change, but if we stick with the major.minor.micro I think the next release should be 1.0.0 to make it clear that a lot of things have changed and we aren't planning on changing the naming significantly again
