### ISSUE TITLE
Invalid field names in connectivity *.MAT file from `dsi_studio_gqi`

### ISSUE THREAD

**Issue by samuelholly** [PennLINC/qsirecon#164]
## Summary
Invalid field names in connectivity *.MAT file from `dsi_studio_gqi`

## Additional details

- QSIRecon version: unstable as of 18th Nov 2024
- Docker version: 4.11
- Singularity version: NA

### What were you trying to do?
Hello, I tried to load the `*_connectivity.mat` output file from `dsi_studio_gqi` pipeline in MATLAB.

### What did you expect to happen?
That MATLAB will load the file.

### What actually happened?
I got an error: `Invalid field name: '4S156Parcels_region_ids'`.

## Reproducing the bug
There are actually two issues.
First, I believe MATLAB variable names cannot start with a number. Manually editing the .mat file and replacing all the "4S156..." with "fS156" solved the problem. 
The second issue I came across when trying to fix the first one is the hyphen in "small-worldness". Replacing it with an underscore solved the problem.

Thank you in advance.

**Comment by tsalo** [comment]
Thanks for reporting @samuelholly.

@mattcieslak I think hdf5 might support numeric keys. WDYT of switching from mat to hdf5?

**Comment by mattcieslak** [comment]
It's funny, the matfile is actually an hdf5 file with some special values in it. Does the connectivity BEP have any suggestions on how to name these? Or are we already too far off from the BEP?

**Comment by tsalo** [comment]
We're mostly just ignoring the BEP because it doesn't recommend bundling different stuff into a single file.

**Comment by mattcieslak** [comment]
I think 3 is definitely the way to go in the long run. Since we aren't using them for the hbcd recon workflow we can maybe do option 1 in the interim and switch to option 3 shortly after. The inode cost of producing hundreds of connectivity matrices should encourage users to not p-hack (maybe?)

**Comment by tsalo** [comment]
That sounds great to me! Do you have a preference on the prefix we should use? `atlas_`?

>The inode cost of producing hundreds of connectivity matrices should encourage users to not p-hack (maybe?)

That _would_ be lovely. In practice, I'm betting people will just start asking for more control over the outputs, but we can just tell them to delete files they don't want after the fact.

**Comment by mattcieslak** [comment]
since users will request these with the `--atlas` flag I think `atlas_` is clear and will work well.

Users can actually control which metrics get calculated via the recon spec [for example here](https://github.com/PennLINC/qsirecon/blob/66a6cf534356d5b001a905b1a22a6deca01ec0cc/qsirecon/data/pipelines/dsi_studio_gqi.yaml#L29) these 2 option will produce 8 different matrices per atlas.

**Comment by tsalo** [comment]
Thanks! I think I found where that would come up and I just replaced any `-`s with `_`s.
