### ISSUE TITLE
Remove unused preprocessing-specific code

### ISSUE THREAD

**Issue by tsalo** [PennLINC/qsirecon#3]
## Summary

The code that is only used by QSIPrep needs to be removed.

**Comment by tsalo** [comment]
@mattcieslak can I remove all of `qsirecon.workflows.anatomical`, `qsirecon.workflows.dwi`, and `qsirecon.workflows.fieldmap`?

**Comment by mattcieslak** [comment]
I'm not sure about this because I am thinking maybe they could be useful if we wanted to further process some of the ingressed anatomical data?

**Comment by tsalo** [comment]
We can always add the workflows back in if they're useful, but my guess is that further anatomical processing would be better done by importing workflows from niworkflows or smriprep.

**Comment by mattcieslak** [comment]
agreed. Let's remove them
