### ISSUE TITLE
Rename `--freesurfer-input` to `--fs-subjects-dir`

### ISSUE THREAD

**Issue by tsalo** [PennLINC/qsirecon#45]
## Summary

It would be great to support sMRIPrep derivatives as well.

**Comment by tsalo** [comment]
Speaking of sMRIPrep- does sMRIPrep output all of the files QSIRecon needs from Freesurfer? If not, is that something we could bring up with the sMRIPrep devs?

**Comment by mattcieslak** [comment]
qsirecon only needs like 3 files from freesurfer. I've run it on smriprep-generated freesurfer outputs and it worked well. I think @araikes has as well

**Comment by tsalo** [comment]
Perhaps a better proposal would be to replace `--freesurfer-input` with `--fs-subjects-dir` and add `--derivatives` to accept sMRIPrep derivatives.
