### ISSUE TITLE
Replace atlas config JSON with BIDS-Atlas datasets

### ISSUE THREAD

**Issue by tsalo** [PennLINC/qsirecon#60]
## Summary

Just a thought. Related to https://github.com/PennLINC/xcp_d/issues/1226 and #12.

**Comment by mattcieslak** [comment]
This wouldn't be too hard of a change. We might need to keep a repo of the mids style metadata for the parcellations somewhere until templateflow is willing to host them

**Comment by tsalo** [comment]
Should have been closed by #123.
