### ISSUE TITLE
Non-qsiprep inputs parsed as BIDS

### ISSUE THREAD

**Issue by smeisler** [PennLINC/qsirecon#74]
## Summary
For example, input HCP1200 and got error for missing `dataset_description.json`. Also, should we rename the `bids_dir` argument to something more broad, like `recon_input`?
## Additional details

- QSIRecon version: My `enh/hcp-ingress branch`
- Docker version:

**Comment by mattcieslak** [comment]
This also reinforces how important it will be to have fake ukbb and hcpya data in the CI tests

**Comment by smeisler** [comment]
This is fixed in #138 , so closing this.
