### ISSUE TITLE
Make the model entity have consistent capitalization for model names

### ISSUE THREAD

**Issue by mattcieslak** [PennLINC/qsirecon#81]
Almost all the model names are acronyms. Some of them are currently capitalized while others aren't (seemingly at random). What would be the most bidsy way to name the files?

**Comment by tsalo** [comment]
I'd go with capitalization for acronyms and lower-case for others.

**Comment by tsalo** [comment]
It's also worth checking with the BEP016 team to make sure everyone uses the same labels.
